spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Это обновит схему базы данных, если нужно
    show-sql: true  # Показать SQL-запросы в логах

  jwt:
    secret: my_secret_key        # Секретный ключ для подписи токенов
    expiration: 86400000         # Срок действия токена в миллисекундах
